// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiskRapor.Data;

#nullable disable

namespace RiskRapor.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240928163841_UpdateMaliBilgilerRelationship")]
    partial class UpdateMaliBilgilerRelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RiskRapor.Models.Anlasmalar", b =>
                {
                    b.Property<int>("AnlasmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnlasmaId"), 1L, 1);

                    b.Property<DateTime>("AnlasmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RiskDegeri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RiskSkoru")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RiskTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnlasmaId");

                    b.ToTable("Anlasmalar");
                });

            modelBuilder.Entity("RiskRapor.Models.Firmalar", b =>
                {
                    b.Property<int>("FirmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FirmaId"), 1L, 1);

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sektor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FirmaId");

                    b.ToTable("Firmalar");
                });

            modelBuilder.Entity("RiskRapor.Models.IsKonulari", b =>
                {
                    b.Property<int>("IsKonuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IsKonuId"), 1L, 1);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnlasmaId")
                        .HasColumnType("int");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskAnalizi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("IsKonuId");

                    b.HasIndex("AnlasmaId");

                    b.ToTable("IsKonulari");
                });

            modelBuilder.Entity("RiskRapor.Models.MaliBilgiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AnlasmaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Gelir")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Gider")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Kar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VergiOrani")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AnlasmaId");

                    b.ToTable("MaliBilgiler");
                });

            modelBuilder.Entity("RiskRapor.Models.IsKonulari", b =>
                {
                    b.HasOne("RiskRapor.Models.Anlasmalar", "Anlasma")
                        .WithMany()
                        .HasForeignKey("AnlasmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anlasma");
                });

            modelBuilder.Entity("RiskRapor.Models.MaliBilgiler", b =>
                {
                    b.HasOne("RiskRapor.Models.Anlasmalar", "Anlasma")
                        .WithMany("MaliBilgiler")
                        .HasForeignKey("AnlasmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anlasma");
                });

            modelBuilder.Entity("RiskRapor.Models.Anlasmalar", b =>
                {
                    b.Navigation("MaliBilgiler");
                });
#pragma warning restore 612, 618
        }
    }
}
